import"./assets/styles-BK7AYJoX.js";import{a as s,i as a}from"./assets/vendor-CJ_tX8LA.js";const r={categoriesList:document.querySelector(".categories"),productsList:document.querySelector(".products"),cartSummaryList:document.querySelector(".cart-summary__list"),notFound:document.querySelector(".not-found"),searchForm:document.querySelector(".search-form"),modal:document.querySelector(".modal"),modalCloseBtn:document.querySelector(".modal__close-btn"),wishListBtn:document.querySelector(".modal-product__btn--wishlist"),cardListBtn:document.querySelector(".modal-product__btn--cart")};s.defaults.baseURL="https://dummyjson.com";async function m(){try{const{data:t}=await s("/products/categories");return t}catch(t){a.error({message:t.message,position:"topRight"})}}async function g(t=1){const o=`/products?limit=12&skip=${(t-1)*12}`;try{const{data:e}=await s(o);return e.products}catch(e){a.error({message:e.message,position:"topRight"})}}async function n(t){try{const{data:o}=await s(`/products/category/${t}`);return o.products}catch(o){a.error({message:o.message,position:"topRight"})}}function y(t){return t.map(({name:o})=>`<li class="categories__item">
   <button class="categories__btn" type="button">${o}</button></li>`).join("")}const _=async()=>{const t=await m();t.unshift({name:"ALL"}),r.categoriesList.insertAdjacentHTML("beforeend",y(t))};function i(t){return t.map(({id:o,images:e,description:c,title:u,brand:d,category:l,price:p})=>`<li class="products__item" data-id="${o}">
    <img class="products__image" src="${e[0]}" alt="${c}"/>
    <p class="products__title">${u}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:</span>${d}</p>
    <p class="products__category">Category:${l} </p>
    <p class="products__price">Price:${p} $</p>
 </li>
`).join("")}const L=async()=>{const t=await g();r.productsList.insertAdjacentHTML("beforeend",i(t))},f=async()=>{const t=await n();r.productsList.insertAdjacentHTML("beforeend",i(t))},h=async t=>{const o=t.target;console.log(o);const e=o.textContent;if(console.log(e),!o.classList.contains("products__btn"))return;console.log(e);const c=await n(e);console.log(c),f()};_();L();r.categoriesList.addEventListener("click",h);
//# sourceMappingURL=index.js.map
