import"./assets/styles-BK7AYJoX.js";import{a as n,i as d}from"./assets/vendor-CJ_tX8LA.js";const o={categoriesList:document.querySelector(".categories"),productsList:document.querySelector(".products"),cartSummaryList:document.querySelector(".cart-summary__list"),notFound:document.querySelector(".not-found"),searchForm:document.querySelector(".search-form"),resetFormBtn:document.querySelector(".search-form__btn-clear"),totalProductsInCart:document.querySelector(".nav__count"),modal:document.querySelector(".modal"),modalProduct:document.querySelector(".modal-product"),modalCloseBtn:document.querySelector(".modal__close-btn"),wishListBtn:document.querySelector(".modal-product__btn--wishlist"),cardListBtn:document.querySelector(".modal-product__btn--cart")};n.defaults.baseURL="https://dummyjson.com";async function g(){try{const{data:t}=await n("/products/categories");return t}catch(t){d.error({message:t.message,position:"topRight"})}}async function p(t=1){const e=`/products?limit=12&skip=${(t-1)*12}`;try{const{data:s}=await n(e);return s.products}catch(s){d.error({message:s.message,position:"topRight"})}}async function L(t,e=1){try{const{data:s}=await n(`/products/category/${t}?limit=12&skip=${(e-1)*12}`);return s.products}catch(s){d.error({message:s.message,position:"topRight"})}}async function y(t){try{const{data:e}=await n(`/products/${t}`);return e}catch(e){d.error({message:e.message,position:"topRight"})}}async function f(t){try{const{data:e}=await n(`/products/search?q=${t}&limit=12`);return e.products}catch(e){d.error({message:e.message,position:"topRight"})}}function h(t){return t.map(({name:e})=>`<li class="categories__item">
   <button class="categories__btn" type="button">${e}</button></li>`).join("")}const b=async()=>{const t=await g();t.unshift({name:"ALL"}),o.categoriesList.insertAdjacentHTML("beforeend",h(t))};function u(t){return t.map(({id:e,images:s,description:r,title:c,brand:a,category:l,price:_})=>`<li class="products__item" data-id="${e}">
    <img class="products__image" src="${s[0]}" alt="${r}"/>
    <p class="products__title">${c}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:</span>${a}</p>
    <p class="products__category">Category:${l} </p>
    <p class="products__price">Price:${_} $</p>
 </li>
`).join("")}const m=async()=>{const t=await p();o.productsList.insertAdjacentHTML("beforeend",u(t))};function C(t){o.productsList.innerHTML="",o.productsList.insertAdjacentHTML("beforeend",u(t))}function S({images:t,description:e,title:s,tags:r,returnPolicy:c,price:a,shippingInformation:l}){return`<img class="modal-product__img" src="${t[0]}" alt="${e}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${s}</p>
        <ul class="modal-product__tags">${r}</ul>
        <p class="modal-product__description">${e}</p>
        <p class="modal-product__shipping-information">Shipping:${l}</p>
        <p class="modal-product__return-policy">Return Policy:${c}</p>
        <p class="modal-product__price">Price:${a} $</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>
`}const $=async t=>{const e=t.target;t.currentTarget.querySelectorAll(".categories__btn").forEach(a=>a.classList.remove("categories__btn--active")),e.classList.add("categories__btn--active");const r=e.textContent;if(e.classList.contains("categories__btn"))r==="ALL"&&m();else return;const c=await L(r);c.length===0&&o.notFound.classList.add("not-found--visible"),C(c)};async function B(t){t.preventDefault();const e=t.target.elements.searchValue.value.trim();e.length===0&&alert("Input shouldn't be empty!");const s=await f(e);s.length===0&&(o.categoriesList.innerHTML="",o.notFound.classList.add("not-found--visible"),o.searchForm.reset()),o.productsList.innerHTML="",o.productsList.insertAdjacentHTML("beforeend",u(s))}const v=async()=>{o.searchForm.reset();const t=await p();o.productsList.innerHTML="",o.productsList.insertAdjacentHTML("beforeend",u(t))},i={CARD_KEY:"cart",WISH_KEY:"wishlist"},A=t=>{let e=JSON.parse(localStorage.getItem(i.CARD_KEY))||[];e.includes(t)||(o.cardListBtn.textContent="Remove from Cart",e.push(t)),localStorage.setItem(i.CARD_KEY,JSON.stringify(e))},E=t=>{let e=JSON.parse(localStorage.getItem(i.CARD_KEY))||[];e.includes(t)&&(o.cardListBtn.textContent="Add to Cart",e=e.slice(1,[t]),localStorage.setItem(i.CARD_KEY,JSON.stringify(e)))},R=async t=>{const e=t.target;if(!e.closest(".products__item"))return;const s=e.closest(".products__item").dataset.id,r=await y(s),c=S(r);o.modalProduct.innerHTML=c,o.modal.classList.add("modal--is-open"),(JSON.parse(localStorage.getItem(i.CARD_KEY))||[]).includes(s)?(o.cardListBtn.textContent="Remove from Cart",o.cardListBtn.addEventListener("click",()=>E(s))):(o.cardListBtn.textContent="Add to Cart",o.cardListBtn.addEventListener("click",()=>{A(s)}))},w=()=>{o.modal.classList.remove("modal--is-open")};b();m();o.categoriesList.addEventListener("click",$);o.productsList.addEventListener("click",R);o.modalCloseBtn.addEventListener("click",w);o.searchForm.addEventListener("submit",B);o.resetFormBtn.addEventListener("click",v);
//# sourceMappingURL=index.js.map
